layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # linkedin: your_username
  # medium: @your_username
  # stackoverflow: your_user_id
  twitter: wombopaper
  # youtube: your_username

topics:
  - name: Unity
    description: "One of the most popular 3D and 2D Game-Engine"
    web_url: https://github.com/topics/unity
    image_url: https://unity.com/themes/unity/images/ui/unity-logo-white.svg

  - name: CSharp
    description: "Programming language made by Microsoft"
    web_url: https://github.com/topics/csharp
    image_url: https://upload.wikimedia.org/wikipedia/commons/4/4f/Csharp_Logo.png

  - name: Blender
    description: "One of the best free and opensource 3D Modeling software"
    web_url: https://blender.org
    image_url: https://download.blender.org/institute/BlenderDesktopLogo.png
